# Site settings
author: Matt
title: My First Blog
header-img: img/home-bg.png
email: mttwright@gmail.com
copyright_name: Matt
description: > # this means to ignore newlines until "baseurl:"
  A Short Subtitle
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mttwright

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
